

export enum Gender {
  MALE = 'Masculino',
  FEMALE = 'Feminino',
  OTHER = 'Outro'
}

export interface Skinfolds {
  triceps: number;
  subscapular: number;
  biceps: number;
  midAxillary: number;
  chest: number;
  abdominal: number;
  suprailiac: number;
  supraspinale: number;
  thigh: number;
  calf: number;
}

export interface BodyMeasurements {
  shoulder: number;
  chest: number;
  waist: number;
  abdomen: number;
  hips: number;
  armRight: number;
  armLeft: number;
  forearmRight: number;
  forearmLeft: number;
  thighRight: number;
  thighLeft: number;
  calfRight: number;
  calfLeft: number;
}

export interface ServicePlan {
  id: string;
  title: string;
  price: number;
  description: string;
  features: string[];
}

export interface DietPreferences {
  dietType: string; // e.g., 'Mediterrânea', 'Low Carb', 'Cetogênica', 'Vegetariana', 'Flexível'
  favoriteFoods: string[]; // Grãos, legumes, carnes específicas
  dislikedFoods: string[];
  mealsPerDay: number;
  waterIntakeGoal: number; // ml
  calorieGoal?: number; // New field for manual calorie target
  trainingFrequency?: number; // Times per week (0-7)
  trainingType?: string; // e.g., 'Musculação', 'Crossfit', 'Corrida', 'Nenhum'
}

export type PaymentStatus = 'PENDING' | 'APPROVED' | 'REJECTED';
export type SubscriptionStatus = 'ACTIVE' | 'INACTIVE' | 'TRIAL' | 'EXPIRED';

export interface ShoppingItem {
  id: string;
  name: string;
  checked: boolean;
}

export interface Recipe {
  id: string;
  name: string;
  ingredients: string;
  instructions?: string;
  portions: number;
  caloriesPerPortion: number;
  macrosPerPortion: { p: number; c: number; f: number };
  micronutrients?: string[];
  imageKeyword?: string;
}

export interface Patient {
  id: string;
  professionalId: string;
  planId?: string; // Links to ServicePlan.id
  name: string;
  email?: string; // Added for login
  password?: string; // Added for login (simulation)
  photoUrl?: string; // Added for profile picture
  age: number;
  gender: Gender;
  weight: number;
  height: number;
  goal: string;
  allergies: string;
  restrictions: string;
  pathologies?: string[];
  familyHistory?: string; // NEW: Histórico Familiar de Doenças
  notes: string;
  history: WeightLog[];
  skinfolds?: Skinfolds;
  measurements?: BodyMeasurements;
  preferences?: DietPreferences;
  paymentStatus?: PaymentStatus; // Pagamento da CONSULTA ao Nutri
  paymentProofUrl?: string; 
  paymentProofType?: 'image' | 'pdf';
  onboardingCompleted?: boolean;
  shoppingList?: ShoppingItem[];
  recipes?: Recipe[]; // New: List of saved recipes
  subscriptionStatus?: SubscriptionStatus; // Mensalidade do APP
  subscriptionExpiry?: string;
}

export interface WeightLog {
  date: string;
  weight: number;
}

export interface MacroNutrients {
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  micronutrients?: string[];
  benefits?: string[]; // New: Nutritional benefits
  usageAdvice?: string[]; // New: How to ingest
}

export interface FoodEntry {
  id: string;
  timestamp: string;
  description: string;
  nutrients: MacroNutrients;
}

export interface MealItem {
  name: string;
  portion: string;
  calories: number;
}

export interface MealSection {
  title: string;
  options: string[]; // Options generated by AI
  selectedOption?: string; // User/Professional selection
  calories: number;
  macros: { p: number; c: number; f: number };
}

export interface MealPlan {
  breakfast: MealSection;
  lunch: MealSection;
  snack: MealSection;
  dinner: MealSection;
  preWorkout: MealSection; // New
  postWorkout: MealSection; // New
  totalCalories: number;
  totalMacros?: { p: number; c: number; f: number }; // Explicit total macros
  micronutrients: string[]; // New: Vitamins and Minerals summary
  shoppingList: string[]; // New
  tips: string[];
}

export interface ProfessionalProfile {
  id: string;
  name: string;
  email: string;
  password?: string; // Added for login
  crn: string;
  specialty: string;
  phone: string;
  bio: string;
  photoUrl?: string;
  plans?: ServicePlan[];
  pixKey?: string; 
  subscriptionStatus?: SubscriptionStatus; // Mensalidade do APP (SaaS)
  subscriptionExpiry?: string;
}

export interface Appointment {
  id: string;
  patientId: string;
  patientName: string;
  date: string;
  time: string;
  type: string;
  status: 'PENDING' | 'CONFIRMED' | 'COMPLETED' | 'CANCELLED';
  videoUrl?: string;
}

export interface Reminder {
  id: string;
  title: string;
  message: string;
  time: string;
  type: 'CONSULTATION' | 'MEDICATION' | 'MEAL' | 'OTHER' | 'WATER';
  active: boolean;
}

// --- WORKOUT TYPES ---
export interface Exercise {
  name: string;
  sets: number;
  reps: string; // Ex: "12" or "10-12" or "Até a falha"
  imageKeyword?: string; // For searching visualization
  notes?: string;
  instructions?: string[]; // Step by step
  tips?: string[]; // Execution tips
}

export interface WorkoutSession {
  id: string;
  patientId: string;
  date: string; // ISO String
  type: 'Full Body' | 'Superior' | 'Inferior' | 'Cardio' | 'Push' | 'Pull' | 'Legs';
  intensity: 'Leve' | 'Moderado' | 'Intenso';
  exercises: Exercise[];
  completed: boolean;
}

// --- CHAT TYPES ---
export interface ChatMessage {
    id: string;
    senderId: string;
    receiverId: string;
    text: string;
    timestamp: string;
    read: boolean;
}

export type ViewState = 'DASHBOARD' | 'PATIENTS' | 'FOOD_LOG' | 'MEAL_PLAN' | 'SHOPPING_LIST' | 'PROGRESS' | 'PROFILE' | 'AGENDA' | 'REMINDERS' | 'MY_RECORD' | 'PREFERENCES' | 'TIPS' | 'WORKOUTS' | 'CHAT' | 'RECIPES' | 'SERVICE_PLANS' | 'PLANS';
